// src/app/enums/tema.enum.ts
export enum Tema {
  BACKEND = 'BACKEND',
  FRONTEND = 'FRONTEND',
  INTELIGENCIA_ARTIFICIAL = 'INTELIGENCIA_ARTIFICIAL',
  SEGURANCA = 'SEGURANCA',
  DEVOPS = 'DEVOPS',
  MOBILE = 'MOBILE',
  UX = 'UX',
  SOBRECARREIRA = 'SOBRECARREIRA',
}
